services:
  api:
    build:
      context: .  # O contexto é o diretório atual onde está o Dockerfile
    environment:
      - DATABASE_URL=postgresql://usuario:usuario@db:5432/db-postgres
    depends_on:
      - db  # A API depende do banco de dados, mas o wait real é feito no ENTRYPOINT
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Monta o diretório do código da aplicação no contêiner
      - /usr/src/app/node_modules  # Garante que o node_modules será criado dentro do contêiner
    working_dir: /usr/src/app  # Define o diretório de trabalho dentro do contêiner
    networks:
      - app-network
    restart: always

  relatorio-api:
    build:
      context: ./relatorio-api  # Diretório da "relatorio-api"
    environment:
      - DATABASE_URL=postgresql://usuario:usuario@db:5432/db-postgres
    depends_on:
      - db
    ports:
      - "3030:3030"
    volumes:
      - ./relatorio-api:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    networks:
      - app-network
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: usuario
      POSTGRES_DB: db-postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Caminho do arquivo de inicialização do banco de dados
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
